name: SonarCloud Analysis

on:
  workflow_call:
    inputs:
      UBUNTU_VERSION:
        default: 'ubuntu-latest'
        required: false
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

permissions:
  pull-requests: read

jobs:
  sonarcloud:
    name: Run SonarCloud Analysis
    runs-on: ${{ inputs.UBUNTU_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4b4d7634dab97dcee0b75763a54a6dc92a9e6bc1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          args: >
            -Dsonar.projectKey=lucio-meira_laravel-sonar-cloud
            -Dsonar.organization=lucio-meira
            -Dsonar.verbose=true
